# NumPy 

NumPy (или Numpy) — это библиотека линейной алгебры для Python. Причина, по которой она так важна для науки о данных с Python, заключается в том, что почти все библиотеки в экосистеме PyData полагаются на NumPy как на один из своих основных строительных блоков.

Numpy также невероятно быстр, так как имеет привязки к библиотекам. Для получения дополнительной информации о том, почему вы хотите использовать массивы вместо списков, ознакомьтесь с этим замечательным постом StackOverflow (http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Мы только изучим основы NumPy, для начала нам нужно его установить!

## Инструкция по установке


**Настоятельно рекомендуется установить Python с помощью дистрибутива Anaconda, чтобы убедиться, что все базовые зависимости (например, библиотеки линейной алгебры) синхронизированы с использованием установки conda. Если у вас есть Anaconda, установите NumPy, перейдя в свой терминал или командную строку и набрав:
Installation Instructions**
    
    conda install numpy
    
** Если у вас нет Anaconda и вы не можете ее установить, обратитесь к [официальной документации Numpy с различными инструкциями по установке] (http://docs.scipy.org/doc/numpy-1.10.1/user/install. html)**

## Использование NumPy

После того, как вы установили NumPy, вы можете импортировать его как библиотеку:

In [1]:
import numpy as np

In [5]:
my_list = [1,2,3]
my_list

[1, 2, 3]

Numpy имеет множество встроенных функций и возможностей. Мы не будем рассматривать их все, а вместо этого сосредоточимся на некоторых наиболее важных аспектах Numpy: векторах, массивах, матрицах и генерации чисел. Начнем с обсуждения массивов.

# Пустые массивы

Массивы NumPy — это основной способ использования Numpy на протяжении всего курса. Массивы Numpy по существу бывают двух видов: векторы и матрицы. Векторы — это строго одномерные массивы, а матрицы — двумерные (но вы должны заметить, что матрица может иметь только одну строку или один столбец).

Давайте начнем наше введение с изучения того, как создавать массивы NumPy.

## Создание массивов NumPy

### Из списка Python

Мы можем создать массив, напрямую преобразовав список или список списков:

In [6]:
print(my_list)

[1, 2, 3]


In [7]:
np.array(my_list)

array([1, 2, 3])

In [65]:
np.array(my_list).dtype

dtype('int32')

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Встроенные методы

Существует множество встроенных способов создания массивов.

### arange

Возвращает равномерно распределенные значения в пределах заданного интервала.

In [ ]:
'Shift'+'Tab'

In [12]:
np.arange(5,20,3)

array([ 5,  8, 11, 14, 17])

In [13]:
np.arange(0,11,2,dtype=float)

array([ 0.,  2.,  4.,  6.,  8., 10.])

### zeros and ones
Генерация массивов нулей или единиц

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
возвращает одномерный массив из указанного количества элементов, равномерно распределенных внутри заданного интервала

In [20]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Создает матрицу идентичности

In [27]:
np.eye(4,3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 
Numpy также имеет множество способов создания массивов случайных чисел:

### rand

Создадим массив заданной формы и заполним его случайными выборками из равномерного распределения
над ``[0, 1)``.

In [28]:
np.random.rand(5)

array([0.52078075, 0.71796691, 0.85966239, 0.97303734, 0.72960792])

In [29]:
[1,2,3]*2

[1, 2, 3, 1, 2, 3]

In [30]:
np.array([1,2,3])*2

array([2, 4, 6])

In [33]:
np.random.rand(20)*4-2

array([-1.18939311, -0.4620497 , -0.08670904, -0.12794137,  1.88217446,
        0.12103411, -1.23380574,  0.14295993,  1.54068777,  1.92142562,
        1.11852303,  0.02018405,  0.14538881,  0.54281289,  0.45617793,
        1.82440513, -0.86622955, -1.29678271,  0.48891151,  1.8740409 ])

In [34]:
np.random.rand(5,5)

array([[0.69143356, 0.22221685, 0.83102003, 0.20149437, 0.94000911],
       [0.14330949, 0.80911485, 0.33205271, 0.18970871, 0.74980368],
       [0.68063059, 0.44289832, 0.4239541 , 0.63325765, 0.70615292],
       [0.83722015, 0.0443467 , 0.07157515, 0.37720415, 0.0112679 ],
       [0.546809  , 0.132357  , 0.38614277, 0.17565036, 0.34552668]])

### randn

Возврат выборки (или выборок) из «стандартного нормального» распределения. В отличие от rand, который является однородным:

In [35]:
np.random.randn(10)

array([-0.17221362, -1.07177825, -0.40164106,  0.31506753, -0.82773789,
        1.60002745, -2.07438389, -1.82705845, -1.15964269, -0.2741614 ])

In [36]:
np.random.randn(5,5)

array([[ 0.65602123,  1.04768002,  0.92787552, -1.50826077, -1.43614776],
       [-0.76424401,  1.15329402,  0.18252825,  0.22510107, -0.09665739],
       [ 0.63426303,  1.50079258, -0.28187962, -0.95046801,  0.16029143],
       [-1.18143291, -1.92417071,  1.16057414,  0.1103974 , -0.41315115],
       [ 0.34761572,  0.65733331,  0.87589019, -0.37285944, -2.40781399]])

In [37]:
np.random.randn(5,5).shape

(5, 5)

### randint
Возвращает случайные целые числа от `низкого` (включительно) до `высокого` (исключая).

In [38]:
np.random.randint(1,100)

20

In [41]:
np.random.randint(1,100,10)

array([78, 42, 71,  1, 29, 46,  9, 78, 46, 42])

## Атрибуты и методы (array) массива

Давайте обсудим некоторые полезные атрибуты и методы или массив:

In [42]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
ranarr

array([ 1,  2, 14, 10, 17, 33, 41,  9, 15, 22])

In [45]:
ranarr.shape

(10,)

## Reshape
Возвращает массив, содержащий те же данные с новой формой.

In [48]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr.reshape(1,25).shape

(1, 25)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### max,min,argmax,argmin
Это полезные методы для нахождения максимальных или минимальных значений. Или найти их индексы, используя argmin или argmax

In [55]:
x = [ 1,  2, 14, 10, 17, 33, 41,  9, 15, 22]

In [57]:
max(x)

41

In [53]:
ranarr

array([ 1,  2, 14, 10, 17, 33, 41,  9, 15, 22])

In [54]:
ranarr.max()

41

In [58]:
ranarr.argmax()

6

In [59]:
ranarr.min()

1

In [60]:
ranarr.argmin()

0

## Shape

Форма — это атрибут, который есть у массивов (а не метод):

In [ ]:
# вектор
arr.shape

In [ ]:
# Обратите внимание на два набора скобок
arr.reshape(1,25)

In [ ]:
arr.reshape(1,25).shape

In [ ]:
arr.reshape(25,1)

In [ ]:
arr.reshape(25,1).shape

### dtype

Вы также можете получить тип данных объекта в массиве:

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [1]:
arr.dtype

NameError: name 'arr' is not defined

In [63]:
[1,'ada']

[1, 'ada']

In [64]:
np.array([1,'ada'])

array(['1', 'ada'], dtype='<U11')